name: Sync Figma Icons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    # Moving env here forces GitHub to guarantee availability inside the container
    env:
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      FIGMA_FILE_URL: "https://www.figma.com/file/MmTgevi8mvxSknkG4PneZ3"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Figma Export Action
        uses: primer/figma-action@v1.0.0-alpha.3
        with:
          args: "format=svg outputDir=./assets/icons/"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Figma Bot"
          git config --global user.email "figmabot@github.com"
          git add ./assets/icons/
          git diff-index --quiet HEAD || git commit -m "chore: automated figma icon update"
          git push
